#!/usr/bin/env python3
from prometheus_client import start_http_server, Gauge
import subprocess
import logging

igpu_frequency_requested = Gauge("igpu_frequency_requested", "Freq MHz req - Requested GPU frequency in MHz (what the system/driver is asking for)")
igpu_frequency_actual = Gauge("igpu_frequency_actual", "Freq MHz act - Actual GPU frequency in MHz (what the GPU is actually running at)")
igpu_interrupts = Gauge("igpu_interrupts", "IRQ /s - Interrupts per second (hardware interrupts generated by the GPU)")
igpu_rc6 = Gauge("igpu_rc6", "RC6 % - Render standby percentage (time GPU spent in low-power RC6 state; higher = more power savings when idle)")
igpu_power_gpu = Gauge("igpu_power_gpu", "Power W gpu - GPU-only power consumption in Watts")
igpu_power_package = Gauge("igpu_power_package", "Power W pkg - Total package power consumption in Watts (includes GPU + other integrated components)")

igpu_engines_render_3d_0_busy = Gauge("igpu_engines_render_3d_0_busy", "RCS % - (Render/Compute Engine) Utilization percentage (3D rendering, compute shaders)")
igpu_engines_render_3d_0_sema = Gauge("igpu_engines_render_3d_0_sema", "RCS se - (Render/Compute Engine) Sema (semaphore wait time percentage)")
igpu_engines_render_3d_0_wait = Gauge("igpu_engines_render_3d_0_wait", "RCS wa - (Render/Compute Engine) Wait time percentage")

igpu_engines_blitter_0_busy = Gauge("igpu_engines_blitter_0_busy", "BCS % - (Blitter/Copy Engine) Utilization percentage (memory-to-memory copies, 2D operations)")
igpu_engines_blitter_0_sema = Gauge("igpu_engines_blitter_0_sema", "BCS se - (Blitter/Copy Engine) Semaphore wait time")
igpu_engines_blitter_0_wait = Gauge("igpu_engines_blitter_0_wait", "BCS wa - (Blitter/Copy Engine) Wait time")

igpu_engines_video_0_busy = Gauge("igpu_engines_video_0_busy", "VCS % - (Video Codec Engine) Utilization percentage (video encoding/decoding)")
igpu_engines_video_0_sema = Gauge("igpu_engines_video_0_sema", "VCS se - (Video Codec Engine) Semaphore wait time")
igpu_engines_video_0_wait = Gauge("igpu_engines_video_0_wait", "VCS wa - (Video Codec Engine) Wait time")

igpu_engines_video_enhance_0_busy = Gauge("igpu_engines_video_enhance_0_busy", "VECS % - (Video Enhancement Engine) Utilization percentage (video post-processing, scaling, color conversion)")
igpu_engines_video_enhance_0_sema = Gauge("igpu_engines_video_enhance_0_sema", "VECS se - (Video Enhancement Engine) Semaphore wait time")
igpu_engines_video_enhance_0_wait = Gauge("igpu_engines_video_enhance_0_wait", "VECS wa - (Video Enhancement Engine) Wait time")

def update(data):
    # Freq MHz req,Freq MHz act,IRQ /s,RC6 %,Power W gpu,Power W pkg,RCS %,RCS se,RCS wa,BCS %,BCS se,BCS wa,VCS %,VCS se,VCS wa,VECS %,VECS se,VECS wa
    igpu_frequency_actual.set(data["Freq MHz act"])
    igpu_frequency_requested.set(data["Freq MHz req"])
    igpu_interrupts.set(data["IRQ /s"])
    igpu_rc6.set(data["RC6 %"])
    igpu_power_gpu.set(data["Power W gpu"])
    igpu_power_package.set(data["Power W pkg"])

    igpu_engines_render_3d_0_busy.set(data["RCS %"])
    igpu_engines_render_3d_0_sema.set(data["RCS se"])
    igpu_engines_render_3d_0_wait.set(data["RCS wa"])

    igpu_engines_blitter_0_busy.set(data["BCS %"])
    igpu_engines_blitter_0_sema.set(data["BCS se"])
    igpu_engines_blitter_0_wait.set(data["BCS wa"])

    igpu_engines_video_0_busy.set(data["VCS %"])
    igpu_engines_video_0_sema.set(data["VCS se"])
    igpu_engines_video_0_wait.set(data["VCS wa"])

    igpu_engines_video_enhance_0_busy.set(data["VECS %"])
    igpu_engines_video_enhance_0_sema.set(data["VECS se"])
    igpu_engines_video_enhance_0_wait.set(data["VECS wa"])

if __name__ == "__main__":
    logging.basicConfig(format="%(asctime)s - %(message)s", level=logging.INFO)
    start_http_server(8080)

    # intel_gpu_top - Display a top-like summary of Intel GPU usage
    # [-c]            Output CSV formatted data.
    # [-s <ms>]       Refresh period in milliseconds (default 1000ms).
    cmd = "intel_gpu_top -c -s {}".format(int(15000))

    process = subprocess.Popen(
        cmd.split(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )

    logging.info(cmd)
    header_line = None
    columns = None

    for line in process.stdout:
        # logging.info(line)

        if ',' in line and any(keyword in line for keyword in ['Freq', 'IRQ', 'RC6', 'Power']):
            header_line = line
            continue

        if not header_line:
            continue

        if not columns:
            columns = [col.strip() for col in header_line.split(',')]

        line = line.strip()
        values = [float(val.strip()) for val in line.split(',')]

        if len(values) != len(columns):
            logging.error(f"Warning: Skipping malformed line (expected {len(columns)} values, got {len(values)})")
            continue

        # logging.info(f"{dict(zip(columns, values))}")
        update(dict(zip(columns, values)))

    process.kill()

    if process.returncode != 0:
        logging.error("Error: " + process.stderr.read().decode("utf-8"))

    logging.info("Finished")
