package main

import (
	"bufio"
	"log"
	"net/http"
	"os/exec"
	"strconv"
	"strings"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// columnGauges maps intel_gpu_top CSV column names to Prometheus gauges.
var columnGauges = map[string]prometheus.Gauge{
	"Freq MHz req": promauto.NewGauge(prometheus.GaugeOpts{
		Name: "igpu_frequency_requested",
		Help: "Freq MHz req - Requested GPU frequency in MHz (what the system/driver is asking for)",
	}),
	"Freq MHz act": promauto.NewGauge(prometheus.GaugeOpts{
		Name: "igpu_frequency_actual",
		Help: "Freq MHz act - Actual GPU frequency in MHz (what the GPU is actually running at)",
	}),
	"IRQ /s": promauto.NewGauge(prometheus.GaugeOpts{
		Name: "igpu_interrupts",
		Help: "IRQ /s - Interrupts per second (hardware interrupts generated by the GPU)",
	}),
	"RC6 %": promauto.NewGauge(prometheus.GaugeOpts{
		Name: "igpu_rc6",
		Help: "RC6 % - Render standby percentage (time GPU spent in low-power RC6 state; higher = more power savings when idle)",
	}),
	"Power W gpu": promauto.NewGauge(prometheus.GaugeOpts{
		Name: "igpu_power_gpu",
		Help: "Power W gpu - GPU-only power consumption in Watts",
	}),
	"Power W pkg": promauto.NewGauge(prometheus.GaugeOpts{
		Name: "igpu_power_package",
		Help: "Power W pkg - Total package power consumption in Watts (includes GPU + other integrated components)",
	}),

	"RCS %":  promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_render_3d_0_busy", Help: "RCS % - (Render/Compute Engine) Utilization percentage (3D rendering, compute shaders)"}),
	"RCS se": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_render_3d_0_sema", Help: "RCS se - (Render/Compute Engine) Semaphore wait time percentage"}),
	"RCS wa": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_render_3d_0_wait", Help: "RCS wa - (Render/Compute Engine) Wait time percentage"}),

	"BCS %":  promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_blitter_0_busy", Help: "BCS % - (Blitter/Copy Engine) Utilization percentage (memory-to-memory copies, 2D operations)"}),
	"BCS se": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_blitter_0_sema", Help: "BCS se - (Blitter/Copy Engine) Semaphore wait time"}),
	"BCS wa": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_blitter_0_wait", Help: "BCS wa - (Blitter/Copy Engine) Wait time"}),

	"VCS %":  promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_video_0_busy", Help: "VCS % - (Video Codec Engine) Utilization percentage (video encoding/decoding)"}),
	"VCS se": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_video_0_sema", Help: "VCS se - (Video Codec Engine) Semaphore wait time"}),
	"VCS wa": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_video_0_wait", Help: "VCS wa - (Video Codec Engine) Wait time"}),

	"VECS %":  promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_video_enhance_0_busy", Help: "VECS % - (Video Enhancement Engine) Utilization percentage (video post-processing, scaling, color conversion)"}),
	"VECS se": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_video_enhance_0_sema", Help: "VECS se - (Video Enhancement Engine) Semaphore wait time"}),
	"VECS wa": promauto.NewGauge(prometheus.GaugeOpts{Name: "igpu_engines_video_enhance_0_wait", Help: "VECS wa - (Video Enhancement Engine) Wait time"}),
}

// headerKeywords are substrings used to detect the CSV header line.
var headerKeywords = []string{"Freq", "IRQ", "RC6", "Power"}

func isHeaderLine(line string) bool {
	if !strings.Contains(line, ",") {
		return false
	}
	for _, kw := range headerKeywords {
		if strings.Contains(line, kw) {
			return true
		}
	}
	return false
}

func splitTrimmed(line string) []string {
	parts := strings.Split(line, ",")
	for i, p := range parts {
		parts[i] = strings.TrimSpace(p)
	}
	return parts
}

func main() {
	http.Handle("/metrics", promhttp.Handler())
	go func() {
		log.Fatal(http.ListenAndServe(":8080", nil))
	}()

	cmd := exec.Command("intel_gpu_top", "-c", "-s", "5000")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatalf("failed to get stdout pipe: %v", err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		log.Fatalf("failed to get stderr pipe: %v", err)
	}

	if err := cmd.Start(); err != nil {
		log.Fatalf("failed to start intel_gpu_top: %v", err)
	}
	log.Println("started: intel_gpu_top -c -s 5000")

	// Drain stderr in background so the process doesn't block.
	go func() {
		s := bufio.NewScanner(stderr)
		for s.Scan() {
			log.Printf("intel_gpu_top stderr: %s", s.Text())
		}
	}()

	var columns []string
	scanner := bufio.NewScanner(stdout)

	for scanner.Scan() {
		line := scanner.Text()

		if isHeaderLine(line) {
			columns = splitTrimmed(line)
			continue
		}

		if columns == nil {
			continue
		}

		values := splitTrimmed(line)
		if len(values) != len(columns) {
			log.Printf("skipping malformed line: expected %d values, got %d", len(columns), len(values))
			continue
		}

		for i, col := range columns {
			g, ok := columnGauges[col]
			if !ok {
				continue
			}
			v, err := strconv.ParseFloat(values[i], 64)
			if err != nil {
				log.Printf("failed to parse value %q for column %q: %v", values[i], col, err)
				continue
			}
			g.Set(v)
		}
	}

	if err := cmd.Wait(); err != nil {
		log.Printf("intel_gpu_top exited with error: %v", err)
	}
	log.Println("finished")
}
